"use client";
import {useEffect,useRef,useState} from "react";
type Patient={hn:string;name:string;birth:string}; type Rec=Patient&{id:number,signedAt:string,status:"completed"|"upload_failed",fileId?:string};
const patients:Patient[]=[{hn:"HN01284",name:"สมหญิง ใจดี",birth:"12 มี.ค. 2533"},{hn:"HN00849",name:"ณัฐชา พิมพ์ใจ",birth:"28 พ.ย. 2528"}];
const sections=[
["เกี่ยวกับการรักษา","ข้าพเจ้ายินยอมให้แพทย์ตรวจ รักษา และฉีดสารเติมเต็ม (Filler) โดยได้รับทราบรายละเอียดผลิตภัณฑ์ ข้อบ่งใช้ บริเวณและปริมาณที่ใช้ รวมถึงค่าใช้จ่ายก่อนรับการรักษา"],
["ความเสี่ยงที่ควรทราบ","การฉีดสารเติมเต็มอาจเกิดการอุดตันของหลอดเลือด หากสารเข้าสู่หลอดเลือดอาจทำให้เนื้อเยื่อขาดเลือด เนื้อตาย การมองเห็นผิดปกติ ตาบอด หรือเกิดภาวะแทรกซ้อนต่อสมองได้ แม้พบได้น้อย ผู้รับบริการต้องแจ้งอาการปวดรุนแรง ผิวซีดคล้ำ หรือการมองเห็นเปลี่ยนแปลงแก่แพทย์ทันที"],
["อาการที่อาจเกิดหลังฉีด","อาจมีอาการปวด บวม แดง ช้ำ คัน ตึง เป็นก้อน หรือไม่สมมาตร รวมถึงการอักเสบหรือติดเชื้อซึ่งอาจเกิดขึ้นภายหลัง หากมีอาการผิดปกติควรติดต่อคลินิกทันที"],
["ยาชาและการรักษา","ผลิตภัณฑ์บางชนิดมี Lidocaine 0.3% และอาจมีการทาหรือฉีดยาระงับความรู้สึกก่อนทำหัตถการ ยาชาอาจทำให้ระคายเคือง แพ้ยา หรือเกิดการอักเสบของเส้นประสาทชั่วคราวหรือถาวรได้"],
["ผลลัพธ์ของการรักษา","ผลการรักษาแตกต่างกันในแต่ละบุคคล โดยทั่วไปอาจคงอยู่ประมาณ 6–18 เดือน ขึ้นกับชนิดผลิตภัณฑ์ ตำแหน่งที่ฉีด การเผาผลาญ และการดูแลตนเอง และไม่สามารถรับประกันผลการรักษาได้"],
["การดูแลหลังฉีด","1. หลีกเลี่ยงการกด นวด หรือสัมผัสบริเวณที่ฉีดโดยไม่จำเป็น\n2. งดออกกำลังกายหนัก ความร้อนจัด ซาวน่า และแอลกอฮอล์ 24–48 ชั่วโมง\n3. หลีกเลี่ยงเลเซอร์หรือหัตถการอื่นตามระยะเวลาที่แพทย์แนะนำ\n4. ดื่มน้ำและพักผ่อนให้เพียงพอ\n5. รับประทานยาและปฏิบัติตามคำแนะนำแพทย์\n6. หากปวดมาก ผิวซีดคล้ำ หรือการมองเห็นผิดปกติ ให้ติดต่อคลินิกทันที"],
["ประวัติการรักษาที่เกี่ยวข้อง","ข้าพเจ้าได้แจ้งประวัติการแพ้ยา โรคประจำตัว การตั้งครรภ์หรือให้นมบุตร ยาที่ใช้อยู่ รวมถึงประวัติหัตถการและสารที่เคยฉีดบริเวณที่จะรักษาแก่แพทย์ตามความเป็นจริง"],
["ข้อควรทราบก่อนยินยอม","ข้าพเจ้ามีโอกาสซักถามข้อสงสัยและได้รับคำอธิบายถึงประโยชน์ ทางเลือก ข้อจำกัด และความเสี่ยงแล้ว เข้าใจว่าไม่สามารถรับประกันผลการรักษา และสามารถเปลี่ยนใจได้ก่อนเริ่มหัตถการ"]];
const confirms=[{h:"การฉีดสารเติมเต็ม",p:"ข้าพเจ้าได้อ่านและเข้าใจข้อมูลทั้งหมด และยินยอมรับการตรวจ รักษา และฉีดสารเติมเต็ม",yes:"ยินยอมรับการรักษา"},{h:"การทายาระงับความรู้สึก",p:"ข้าพเจ้ายินยอมให้ทายาระงับความรู้สึก และรับทราบว่าอาจเกิดการระคายเคืองหรืออาการแพ้",yes:"ยินยอมให้ทายาชา"},{h:"การใช้ยาระงับความรู้สึก",p:"ข้าพเจ้ายินยอมให้ใช้ยาระงับความรู้สึก และรับทราบความเสี่ยงต่อเส้นประสาทซึ่งอาจเกิดขึ้นชั่วคราวหรือถาวร",yes:"ยินยอมให้ใช้ยาระงับความรู้สึก"}];
export default function Home(){
 const[view,setView]=useState("patients"),[q,setQ]=useState(""),[patient,setPatient]=useState<Patient|null>(null),[ans,setAns]=useState<(boolean|null)[]>([null,null,null]),[add,setAdd]=useState(false),[sign,setSign]=useState(false),[signed,setSigned]=useState(false),[recs,setRecs]=useState<Rec[]>([]),[notice,setNotice]=useState(""),[fail,setFail]=useState(false); const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false);
 useEffect(()=>{const s=localStorage.getItem("michiko-consents");if(s)setRecs(JSON.parse(s))},[]); const save=(r:Rec[])=>{setRecs(r);localStorage.setItem("michiko-consents",JSON.stringify(r))};
 const choose=(p:Patient)=>{setPatient(p);setAns([null,null,null]);setSigned(false);setView("consent");window.scrollTo(0,0)};
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*300/r.height}};
 const down=(e:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=true;const c=e.currentTarget.getContext("2d")!,p=pos(e);c.beginPath();c.moveTo(p.x,p.y);e.currentTarget.setPointerCapture(e.pointerId)}; const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=e.currentTarget.getContext("2d")!,p=pos(e);c.lineWidth=3;c.lineCap="round";c.strokeStyle="#26372f";c.lineTo(p.x,p.y);c.stroke()};
 const submit=()=>{if(!patient)return;const r:Rec={...patient,id:Date.now(),signedAt:new Date().toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short"}),status:fail?"upload_failed":"completed",...(fail?{}:{fileId:`DRV-${Date.now().toString().slice(-7)}`})};save([r,...recs]);setNotice(fail?"สร้าง PDF แล้ว แต่ยังอัปโหลดไป Google Drive ไม่สำเร็จ":"บันทึก Consent และสร้าง PDF สำเร็จแล้ว");setFail(false);setView("history");window.scrollTo(0,0)};
 return <div className="shell"><aside><div className="brand"><i>M</i><span><b>Michiko</b><small>SMART LEDGER</small></span></div><nav><button>⌂ ภาพรวม</button><button className={view!=="history"?"active":""} onClick={()=>setView("patients")}>✎ Digital Consent</button><button className={view==="history"?"active":""} onClick={()=>setView("history")}>◷ ประวัติ Consent</button></nav><div className="clinic">MC <span><b>Michiko Clinic</b><small>ผู้ดูแลระบบ</small></span></div></aside><main><header><button className="mobileM">M</button><div><em>MICHIKO SMART LEDGER</em><h1>{view==="patients"?"Digital Consent":view==="consent"?"แบบยินยอมรับการฉีดสารเติมเต็ม":"ประวัติ Consent"}</h1></div><span>◷ 19 สิงหาคม 2569</span></header>
 {view==="patients"&&<section className="page"><div className="hero"><div><em>เริ่มต้นเอกสารใหม่</em><h2>ค้นหาผู้รับบริการ</h2><p>ค้นหาด้วย HN หรือชื่อ–นามสกุล เพื่อเริ่มทำ Consent</p></div><button className="primary" onClick={()=>setAdd(true)}>＋ เพิ่มผู้รับบริการ</button></div><div className="search"><label>ค้นหาผู้รับบริการ</label><div>⌕ <input value={q} onChange={e=>setQ(e.target.value)} placeholder="กรอก HN หรือชื่อ–นามสกุล"/></div><small>ไม่ต้องใช้หมายเลขโทรศัพท์</small></div><h3 className="list-title">ผู้รับบริการล่าสุด</h3>{patients.filter(p=>(p.hn+p.name).toLowerCase().includes(q.toLowerCase())).map(p=><button className="patient" key={p.hn} onClick={()=>choose(p)}><i>{p.name[0]}</i><span><b>{p.name}</b><small>{p.hn} · เกิด {p.birth}</small></span><strong>เริ่ม Consent ›</strong></button>)}</section>}
 {view==="consent"&&patient&&<section className="consent"><button className="back" onClick={()=>setView("patients")}>‹ กลับไปเลือกผู้รับบริการ</button><div className="patientbar"><div><i>{patient.name[0]}</i><span><small>ผู้รับบริการ</small><b>{patient.name}</b></span></div><span><small>HN</small><b>{patient.hn}</b></span><span><small>วันเกิด</small><b>{patient.birth}</b></span><span><small>เอกสาร</small><b>Filler Consent v1</b></span></div><div className="progress"><i style={{width:`${signed?100:18+ans.filter(Boolean).length*24}%`}}/></div><div className="paper"><div className="title"><b>แบบยินยอมการรักษา</b><h2>การฉีดสารเติมเต็ม (Filler)</h2><p>กรุณาอ่านข้อมูลทุกส่วนให้ครบถ้วนก่อนตัดสินใจ</p></div>{sections.map((s,i)=><article key={s[0]}><i>{i+1}</i><div><h3>{s[0]}</h3><p>{s[1]}</p></div></article>)}<div className="confirm"><em>การตัดสินใจของผู้รับบริการ</em><h2>กรุณายืนยันทีละข้อ</h2><p>อ่านข้อความให้ครบก่อนเลือก การเลือก “ไม่ยินยอม” จะหยุดขั้นตอนและแจ้งเจ้าหน้าที่</p>{confirms.map((c,i)=><div className={`choice ${ans[i]===false?"declined":""}`} key={c.h}><i>{i+1}</i><div><h3>{c.h}</h3><p>{c.p}</p><div className="buttons"><button className={ans[i]===true?"yes":""} onClick={()=>setAns(a=>a.map((x,j)=>j===i?true:x))}>✓ {c.yes}</button><button className={ans[i]===false?"no":""} onClick={()=>setAns(a=>a.map((x,j)=>j===i?false:x))}>× ไม่ยินยอม</button></div>{ans[i]===false&&<mark>กรุณาแจ้งเจ้าหน้าที่ก่อนดำเนินการต่อ</mark>}</div></div>)}</div><div className="signbox"><div><em>ขั้นตอนสุดท้าย</em><h2>ลงลายมือชื่อ</h2><p>ข้าพเจ้ารับรองว่าได้อ่านและเข้าใจข้อมูลข้างต้น ได้รับโอกาสซักถาม และตัดสินใจโดยสมัครใจ</p></div><button disabled={ans.some(a=>a!==true)} onClick={()=>setSign(true)} className={signed?"done":""}>{signed?"✓ ลงลายมือชื่อแล้ว":"✎ กดเพื่อลงลายมือชื่อ"}</button></div><div className="submit"><label><input type="checkbox" checked={fail} onChange={e=>setFail(e.target.checked)}/> ทดสอบ Drive ขัดข้อง</label><button className="primary" disabled={!signed||ans.some(a=>a!==true)} onClick={submit}>ยืนยันและสร้าง PDF ›</button></div></div></section>}
 {view==="history"&&<section className="page">{notice&&<div className={`toast ${notice.includes("ไม่สำเร็จ")?"err":""}`}>{notice}<button onClick={()=>setNotice("")}>×</button></div>}<div className="hero"><div><em>เอกสารที่บันทึกแล้ว</em><h2>ประวัติ Consent</h2><p>ค้นหา เปิด PDF และติดตามสถานะการอัปโหลด</p></div><button className="primary" onClick={()=>setView("patients")}>＋ สร้าง Consent ใหม่</button></div>{recs.length===0?<div className="empty"><b>ยังไม่มีเอกสารที่เซ็นแล้ว</b><p>เอกสารใหม่จะปรากฏที่นี่หลังยืนยันลายมือชื่อ</p></div>:recs.map(r=><div className="record" key={r.id}><i>PDF</i><div><b>{r.name}</b><small>{r.hn} · Filler Consent v1</small><small>ลงนาม {r.signedAt}</small></div><mark className={r.status}>{r.status==="completed"?"● เก็บใน Drive แล้ว":"! รออัปโหลด"}</mark>{r.status==="upload_failed"?<button onClick={()=>save(recs.map(x=>x.id===r.id?{...x,status:"completed",fileId:`DRV-${Date.now()}`}:x))}>↻ อัปโหลดอีกครั้ง</button>:<a href="https://drive.google.com" target="_blank">เปิดเอกสาร ↗</a>}</div>)}</section>}
 </main>{add&&<div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);choose({hn:String(f.get("hn")),name:String(f.get("name")),birth:String(f.get("birth"))});setAdd(false)}}><button type="button" className="x" onClick={()=>setAdd(false)}>×</button><em>ผู้รับบริการใหม่</em><h2>เพิ่มข้อมูลผู้รับบริการ</h2><label>HN<input required name="hn" placeholder="เช่น HN01285"/></label><label>ชื่อ–นามสกุล<input required name="name"/></label><label>วันเดือนปีเกิด<input required name="birth" type="date"/></label><button className="primary">บันทึกและเลือก Consent</button></form></div>}{sign&&<div className="overlay"><div className="modal signature"><button className="x" onClick={()=>setSign(false)}>×</button><em>ลายมือชื่อผู้รับบริการ</em><h2>เซ็นชื่อในกรอบด้านล่าง</h2><p>ใช้ปากกา Stylus หรือนิ้วมือ</p><canvas ref={canvas} width="800" height="300" onPointerDown={down} onPointerMove={move} onPointerUp={()=>drawing.current=false}/><div className="signatureActions"><button onClick={()=>canvas.current?.getContext("2d")?.clearRect(0,0,800,300)}>ล้างแล้วเซ็นใหม่</button><button className="primary" onClick={()=>{setSigned(true);setSign(false)}}>ยืนยันลายมือชื่อ</button></div></div></div>}</div>}
